title: The Pragmatic Guide to State Machines
description: A practical guide to understanding and implementing state machines in software development

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _layouts
  - assets 