title: The Pragmatic Guide to State Machines
email: your-email@example.com
description: >-
  A practical guide to understanding and implementing state machines in software development.
  Learn from basics to advanced concepts with real-world examples.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO Settings
author: Your Name
lang: en
timezone: UTC

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Your Name"
      description: "A practical guide to understanding and implementing state machines in software development"
      keywords: "state machine, statechart, software development, programming, design patterns, UML, modeling"

# Minima theme settings
minima:
  skin: classic
  date_format: "%b %-d, %Y"
  social_links:
    - title: GitHub
      icon: github
      url: https://statecharts.online


# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _layouts
  - assets
